version: '3.8'
services:
  pchem-server:
    build:
      context: .          
      dockerfile: Dockerfile
      network: host      
    ports:
      - "3335:3335"
    image: pchem-server


  

    
